id: A426D2B52
title: Wrathful Guru Mantra Visualization
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:44:55.052328
  last_modified_at: 2022-03-01 03:44:55.052332
